### ISSUE TITLE
Ignore .DS_store and other dot files

### ISSUE THREAD

**Issue by client9** [jeonglee/Libinjection#1]
Hi Chris,

good work here.

I would add a `.gitignore` file and add .DS_Store and all the other dot files that are from your personal environment.  Then `git rm`  them -- it will make your repo cleaner.

regards!

n

**Comment by jeonglee** [comment]
Hi Nick,

Done. 

I've added the performance test I used to get 450,000+ tests per second to Main.java (commented out) in case you want to test it.

Chris
